
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgunnulcgnwtfgwcrynv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ndW5udWxjZ253dGZnd2NyeW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MjQyOTUsImV4cCI6MjA2NzAwMDI5NX0.8vpurLIE9Yllnq3dM0edN_infci0-Sz7YLJt3p-zvW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
